
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

// Card01
import Card01 from '../views/cards/Card01'

const inter = Inter({ subsets: ['latin'] })

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Card01/>
      </main>
    </>
  )
}
